export build_dir=./build
export build_output_dir=$build_dir/output
export build_output_bin_dir=$build_output_dir/bin
export parameterized_base_rust=src/parameterized_base_deps/rust_traits_serializable 

export default_execute_file=parameterized_base
