#!/usr/bin/env python3
# -*- coding:utf-8 -*-
########################################################################
#
# Copyright (c) 2025 xx.com, Inc. All Rights Reserved
#
########################################################################
"""
Author : xuechengyun
E-mail : xuechengyun@gmail.com
Date   : 2025/01/10 21:49:47
Desc   :
"""

import sys
import os
import logging

CUR_DIR = os.path.dirname(os.path.abspath(__file__))
LOG_FORMAT = '''[%(levelname)s] [%(asctime)s] [%(threadName)s] [%(name)s] '''
LOG_FORMAT += '''[%(filename)s:%(funcName)s:%(lineno)d]: %(message)s'''
logging.basicConfig(
    stream=sys.stderr,
    level=logging.INFO,
    format=LOG_FORMAT
)

# code generated by llm from poe.com

import requests
from bs4 import BeautifulSoup
import re

def fetch_cpp_idioms():
    url = "https://en.wikibooks.org/wiki/More_C%2B%2B_Idioms"
    
    # 获取页面内容
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    
    # 找到目录部分
    toc = soup.find('div', {'id': 'mw-content-text'}).find('ol')
    
    # 存储idioms的列表
    idioms = []
    
    # 遍历所有列表项
    for item in toc.find_all(['p', 'li']):
        text = item.get_text().strip()
        # 去除 "TODO" 标记
        # text = re.sub(r'\s*TODO\s*', '', text)
        # 去除空括号
        text = re.sub(r'\s*\(\s*\)\s*', '', text)
        # 如果文本不为空且不是章节标题，添加到列表
        if text and not text.startswith('['): 
            idioms.append(text)
    
    # 打印编号的idioms列表
    for i, idiom in enumerate(idioms, 1):
        print(f"{i}. {idiom}")
    
    return idioms

def main():
    # 执行函数
    idioms = fetch_cpp_idioms()

    

if __name__ == '__main__':
    main()

